DROP TABLE IF EXISTS user_data.phone_book;

CREATE TABLE user_data.phone_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    phone_number VARCHAR(20) NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone_name VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
  );
